Fixed broken directory cleanup on failed initiation, needs further testing

diff --git a/aq-init b/aq-init
--- a/aq-init
+++ b/aq-init
@@ -13,7 +13,7 @@ set -e # Exit script immediately on first error.
 # Version:      0.1.0
 # Notes:        This script will create a new project directory with the this name into
 #               the current working directory. It will also create a basic Python
-#               project configuration with Poetry. It will also create a .env file for 
+#               project configuration with Poetry. It will also create a .env file for
 #               environment variables, a README.md file, a check_environment.py file for
 #               testing the environment setup, a makefile for building the project, and a
 #               .gitignore file for ignoring files in git.
@@ -34,6 +34,18 @@ set -e # Exit script immediately on first error.
 
 # Get project name from command line arg
 PROJECT=$1
+
+# Initialize PROJECT_DIR
+PROJECT_DIR=""
+
+# Trap errors and perform cleanup
+cleanup() {
+    if [ -n "$PROJECT_DIR" ] && [ -d "$PROJECT_DIR" ]; then
+        echo "Cleaning up temporary project directory..."
+        rm -rf "${PROJECT_DIR:?}"
+    fi
+}
+trap cleanup ERR
 
 #### Sanity check project metadata ####
 
diff --git a/aq-minit b/aq-minit
--- a/aq-minit
+++ b/aq-minit
@@ -36,6 +36,18 @@ set -e # Exit script immediately on first error.
 # Get project name from command line arg
 PROJECT=$1
 
+# Initialize PROJECT_DIR
+PROJECT_DIR=""
+
+# Trap errors and perform cleanup
+cleanup() {
+    if [ -n "$PROJECT_DIR" ] && [ -d "$PROJECT_DIR" ]; then
+        echo "Cleaning up temporary project directory..."
+        rm -rf "${PROJECT_DIR:?}"
+    fi
+}
+trap cleanup ERR
+
 #### Sanity check project metadata ####
 
 # Define some basic sanity check functions
@@ -95,6 +107,7 @@ SCRIPTPATH="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/nu
 CURRENT_WORKING_DIR="$(pwd)"
 
 PROJECT_DIR="$(create_project_dir "$PROJECT" "$SCRIPTPATH")"
+
 # cd to the project directory
 cd "$PROJECT_DIR" || exit
 
@@ -308,7 +321,7 @@ NEW_PROJECT_DIR="$CURRENT_WORKING_DIR"/"$PROJECT"
 mkdir "$NEW_PROJECT_DIR"
 
 # Copy the project folder to the new project folder
-cp -Ra "$PROJECT_DIR"/. "$NEW_PROJECT_DIR" 
+cp -Ra "$PROJECT_DIR"/. "$NEW_PROJECT_DIR"
 
 # Move to SCRIPTPATH
 cd "$SCRIPTPATH" || exit
